### ISSUE TITLE
能否提供一个mac系统的安装包

### ISSUE THREAD

**Issue by 27954741** [pengtianabc/wireshark-gm#10]
mac下编译实在不过，很多包下载失败，能否提供一个mac的包或者需要的第三方库文件
谢谢

**Comment by pengtianabc** [comment]
> mac下编译实在不过，很多包下载失败，能否提供一个mac的包或者需要的第三方库文件
> 谢谢

没有Mac环境，只能自己想办法了，建议去看下wireshark官方提供的资料

**Comment by 27954741** [comment]
[ 74%] Building CXX object ui/qt/CMakeFiles/qtui.dir/about_dialog.cpp.o
[ 74%] Building CXX object ui/qt/CMakeFiles/qtui.dir/accordion_frame.cpp.o
[ 74%] Building CXX object ui/qt/CMakeFiles/qtui.dir/address_editor_frame.cpp.o
[ 74%] Building CXX object ui/qt/CMakeFiles/qtui.dir/bluetooth_att_server_attributes_dialog.cpp.o
/Users/dingxd/tools/wireshark-gm-wireshark-2.9.0-gm.3/ui/qt/bluetooth_att_server_attributes_dialog.cpp:366:22: error: 
      'grabWidget' is deprecated: Use QWidget::grab() instead [-Werror,-Wdeprecated-declarations]
    image = QPixmap::grabWidget(ui->tableTreeWidget);
                     ^
/usr/local/opt/qt5/lib/QtGui.framework/Headers/qpixmap.h:123:5: note: 'grabWidget' has been explicitly marked
      deprecated here
    QT_DEPRECATED_X("Use QWidget::grab() instead")
    ^
/usr/local/opt/qt5/lib/QtCore.framework/Headers/qglobal.h:294:33: note: expanded from macro 'QT_DEPRECATED_X'
#  define QT_DEPRECATED_X(text) Q_DECL_DEPRECATED_X(text)
                                ^
/usr/local/opt/qt5/lib/QtCore.framework/Headers/qcompilerdetection.h:649:55: note: expanded from macro
      'Q_DECL_DEPRECATED_X'
#    define Q_DECL_DEPRECATED_X(text) __attribute__ ((__deprecated__(text)))
                                                      ^
1 error generated.
make[2]: *** [ui/qt/CMakeFiles/qtui.dir/bluetooth_att_server_attributes_dialog.cpp.o] Error 1
make[1]: *** [ui/qt/CMakeFiles/qtui.dir/all] Error 2
make: *** [all] Error 2

**Comment by 27954741** [comment]
mac下编译出错了，麻烦看一下，谢谢

**Comment by 27954741** [comment]
[ 74%] Building CXX object ui/qt/CMakeFiles/qtui.dir/about_dialog.cpp.o
[ 74%] Building CXX object ui/qt/CMakeFiles/qtui.dir/accordion_frame.cpp.o
[ 74%] Building CXX object ui/qt/CMakeFiles/qtui.dir/address_editor_frame.cpp.o
[ 74%] Building CXX object ui/qt/CMakeFiles/qtui.dir/bluetooth_att_server_attributes_dialog.cpp.o
/Users/aaa/tools/wireshark-gm-wireshark-2.9.0-gm.3/ui/qt/bluetooth_att_server_attributes_dialog.cpp:366:22: error: 
      'grabWidget' is deprecated: Use QWidget::grab() instead [-Werror,-Wdeprecated-declarations]
    image = QPixmap::grabWidget(ui->tableTreeWidget);
                     ^
/usr/local/opt/qt5/lib/QtGui.framework/Headers/qpixmap.h:123:5: note: 'grabWidget' has been explicitly marked
      deprecated here
    QT_DEPRECATED_X("Use QWidget::grab() instead")
    ^
/usr/local/opt/qt5/lib/QtCore.framework/Headers/qglobal.h:294:33: note: expanded from macro 'QT_DEPRECATED_X'
#  define QT_DEPRECATED_X(text) Q_DECL_DEPRECATED_X(text)
                                ^
/usr/local/opt/qt5/lib/QtCore.framework/Headers/qcompilerdetection.h:649:55: note: expanded from macro
      'Q_DECL_DEPRECATED_X'
#    define Q_DECL_DEPRECATED_X(text) __attribute__ ((__deprecated__(text)))
                                                      ^
1 error generated.
make[2]: *** [ui/qt/CMakeFiles/qtui.dir/bluetooth_att_server_attributes_dialog.cpp.o] Error 1
make[1]: *** [ui/qt/CMakeFiles/qtui.dir/all] Error 2
make: *** [all] Error 2
[err.log](https://github.com/pengtianabc/wireshark-gm/files/3535519/err.log)

**Comment by pengtianabc** [comment]
QT版本太新了

**Comment by 27954741** [comment]
多谢,已搞定,mac版本的wireshark-gm

**Comment by catbro666** [comment]
> 多谢,已搞定,mac版本的wireshark-gm

兄弟，能否分享一下成果

**Comment by catbro666** [comment]
> 多谢,已搞定,mac版本的wireshark-gm

你用什么版本的Qt编的，我也碰到这个问题了

**Comment by 27954741** [comment]
qt改成5.9.5版本了,怎么发给你

**Comment by pengtianabc** [comment]
> qt改成5.9.5版本了,怎么发给你
issue可以接附件，试试吧

**Comment by catbro666** [comment]
> qt改成5.9.5版本了,怎么发给你

多谢了，我也搞定了哈，握爪  : )

**Comment by 27954741** [comment]
附件不能超过10M
链接:https://pan.baidu.com/s/1stSo5kgjq-2aKImHXpo6Zg  密码:pq3w

> > qt改成5.9.5版本了,怎么发给你
> > issue可以接附件，试试吧

附件不能超过10M
链接:https://pan.baidu.com/s/1stSo5kgjq-2aKImHXpo6Zg  密码:pq3w

**Comment by 27954741** [comment]
> > qt改成5.9.5版本了,怎么发给你
> > issue可以接附件，试试吧

附件不能超过10M
链接:https://pan.baidu.com/s/1stSo5kgjq-2aKImHXpo6Zg  密码:pq3w

**Comment by Asura88** [comment]
发一下mac版本的呀

**Comment by 27954741** [comment]
我是10.13的包




------------------&nbsp;Original&nbsp;------------------

**Comment by gracesun** [comment]
> > qt改成5.9.5版本了,怎么发给你
> 
> 多谢了，我也搞定了哈，握爪 : )

老师，您好，能否发一下mac版本的wireshark-gm版本

**Comment by blaisewang** [comment]
mac 版 https://github.com/pengtianabc/wireshark-gm/releases
