### ISSUE TITLE
使用360国密浏览器测试国密双向SSL时抓包过程中似乎出现了错误

### ISSUE THREAD

**Issue by Nu1i** [pengtianabc/wireshark-gm#11]
使用360国密浏览器测试国密双向SSL时抓包显示图片中的数据，但数据能够正常收发，证书为CFCA证书，颁发者CFCA TEST SM2 OCA1，360国密浏览器版本7.1.1.782。

**Comment by Nu1i** [comment]
Expert Info (Error/Malformed): Vector length 12357 is too large, truncating it to 69

**Comment by pengtianabc** [comment]
建议提供pcap包和截图

**Comment by Nu1i** [comment]
附件上传似乎一直有问题。

**Comment by pengtianabc** [comment]
当时写的时候只做了几个套件和SSL版本的识别，猜测可能是因为那部分的封包格式没做解析，所以有问题，12357这个值太大了，不太像是证书信息，更像是解析错误

**Comment by zyxs2018** [comment]
![1574770969(1)](https://user-images.githubusercontent.com/38100091/69896696-418fbc00-137d-11ea-8972-c46683ce75b3.png)
