### ISSUE TITLE
国密协议解析似乎有问题--附带数据保存

### ISSUE THREAD

**Issue by neighbads** [pengtianabc/wireshark-gm#12]
数据保存：
[gmtls.zip](https://github.com/pengtianabc/wireshark-gm/files/5626448/gmtls.zip)

与标准的 gm 服务正常连接，仔细看数据包内容也没有问题，但是 wireshark-gm 不能正常解析。

**Comment by pengtianabc** [comment]
这是wiereshark配置问题, 右键-解码为-把pcap中的源目的那儿都修改为SSL, 就可以了
因为5445那个端口被默认解析为其他协议了
![image](https://user-images.githubusercontent.com/13852782/100819749-b9f4f580-3487-11eb-82cd-7cec45ae5e31.png)
