### ISSUE TITLE
是否还会继续维护 wireshark-gm 呢

### ISSUE THREAD

**Issue by blaisewang** [pengtianabc/wireshark-gm#13]

**Comment by pengtianabc** [comment]
维护指的是什么呢？
- 如果指的是跟随主线版本升级，那其实问题不大，因为改动地方也就固定的那几个地方，如果能自己编译，人肉patch就行了（之前我已经准备把这功能patch到wireshark官方了，但是由于他们的git有问题，所以一直无法完成这个操作，也就搁置了，github上的这个库只是他们的一个mirror，所以没法pr）
- 如果指的是一些提出的特定feature，因为现在没有做国密相关的，可能就不会增加了

**Comment by blaisewang** [comment]
sorry，手抖没写完就发布了，这个关掉了

**Comment by blaisewang** [comment]
#14 这个是完整的提议
