### ISSUE TITLE
是否还会继续维护 wireshark-gm 呢？

### ISSUE THREAD

**Issue by blaisewang** [pengtianabc/wireshark-gm#14]
我 fork 了 Wireshark 的 upstream，基于最新的稳定版 3.4.5 pick 了你国密支持的 commit，修了 cipher suites 位置不对导致 GitHub Actions 测试跑不过的问题，新增了一个 action job 把构建完的可执行文件上传 releases，这样就可以提供构建好的 macos 版和 win64 版了。我的 repo：https://github.com/blaisewang/wireshark

如果还继续维护的话，我可以开一个 pr 把上述改动提交到你的 repo，这样可以方便更多用户。

**Comment by pengtianabc** [comment]
可以的话我可以把你添加到contributer里，这样你可以直接操作，因为fork的库不太好找到，所以想让其他人看到的概率比较低，最好的解决方案还是把这个支持patch到官方去

**Comment by blaisewang** [comment]
> 可以的话我可以把你添加到contributer里

可以，我下周有时间提交一下。

> 最好的解决方案还是把这个支持patch到官方去

感觉大概率不会被接受吧，感觉蚂蚁的 draft 才会成为之后国密的主流，https://tools.ietf.org/html/rfc8998

**Comment by pengtianabc** [comment]
contributer已经添加了，你可以把pr提交过来

我刚刚去确认了下，wireshark的官方库现在迁移到gitlab了，只要我们合并了主线代码，合并后提交代码到官方会容易很多。

至于会不会被接收这个就要看了，因为现在的实现是写到国家标准里去了，我们只是做了协议解析支持而已，讲简单一点可能就只是个国产协议解析器。

**Comment by blaisewang** [comment]
我的计划是 rebase upstream，基于已发布的最新稳定版的 tag 拉取 gm 分支 pick 上述改动，新增 gm tag。rebase upstream 这一步用 pr 不太好搞吧，我直接操作 repo 了？
