### ISSUE TITLE
Centos 7 编译安装 wireshark-gm 报错

### ISSUE THREAD

**Issue by lijiachang** [pengtianabc/wireshark-gm#18]
Hi！
在经历过一系列的报错缺少组件，解决前面的问题后。到了这里不知道该怎么办了，有没有办法跳过QT5的依赖？：

PS：我希望在Linux中使用Python3操作命令行版本wireshark-gm，进行抓包和解析。so ，我并不需要用户界面GUI

![编译进度](https://user-images.githubusercontent.com/28041718/119924469-39323480-bfa6-11eb-82a7-47c753be86ac.jpg)

**Comment by pengtianabc** [comment]
1. -DBUILD_wireshark=OFF 参见 [官方文档](https://www.wireshark.org/docs/wsdg_html_chunked/ChToolsCMake.html )

2. [INSTALL#7](https://github.com/pengtianabc/wireshark-gm/blob/master-3.4-gm/INSTALL)

**Comment by lijiachang** [comment]
> 1. -DBUILD_wireshark = OFF参见[官方文档](https://www.wireshark.org/docs/wsdg_html_chunked/ChToolsCMake.html)
> 2. [安装＃7](https://github.com/pengtianabc/wireshark-gm/blob/master-3.4-gm/INSTALL)

感谢您的回复
