### ISSUE TITLE
wireshark-gm版本目前似乎不支持ipsec gm解析？

### ISSUE THREAD

**Issue by beirvin** [pengtianabc/wireshark-gm#19]
wireshark-gm版本目前似乎不支持ipsec gm解析？如下图所示，找不到解析国密SM4和SM3的设置：
![Image 1](https://user-images.githubusercontent.com/73393321/123255762-cb384900-d522-11eb-9683-276b73315a54.png)
![Image 2](https://user-images.githubusercontent.com/73393321/123255779-cecbd000-d522-11eb-8516-ede74fecc93f.png)

**Comment by pengtianabc** [comment]
是的，没有这部分解析，因为当前值做了数据段类型解析，但是数据的解析依赖算法，算法的话和wireshark底层的ssl库有强关联，当前wireshark使用的gnutls，需要它支持对应算法才可以

**Comment by beirvin** [comment]
> 
> 
> 是的，没有这部分解析，因为当前值做了数据段类型解析，但是数据的解析依赖算法，算法的话和wireshark底层的ssl库有强关联，当前wireshark使用的gnutls，需要它支持对应算法才可以
好的，知道了，希望后面能够支持Ipsec esp gm国密解密。
PS: 原想着TLS支持gm国密解析，Ipsec就是移植适配的。
