### ISSUE TITLE
release里面有较新的自己编译的exe

### ISSUE THREAD

**Issue by yunlai** [pengtianabc/wireshark-gm#2]
这个exe在哪里？

**Comment by pengtianabc** [comment]
@yunlai 
![360 16241223252946](https://user-images.githubusercontent.com/13852782/46051175-79dcae80-c16a-11e8-954c-02f83211575b.png)
![360 183605118879122](https://user-images.githubusercontent.com/13852782/46051176-7a754500-c16a-11e8-96b1-9695f3b9d2d9.png)

**Comment by yunlai** [comment]
谢谢，我也按照教程编过了

**Comment by shenggithub** [comment]
exe是用什么软件生成的安装包？vs自带的么？

**Comment by tengliu0929** [comment]
我还是没有找到Windows branch，不会是windows native这个分枝吧

**Comment by pengtianabc** [comment]
> 我还是没有找到Windows branch，不会是windows native这个分枝吧

https://github.com/pengtianabc/wireshark-gm/releases/download/v3.3.0-gm/Wireshark-win32-3.3.0-gm.exe
