### ISSUE TITLE
GB/T 38636-2020 定义的密码套件不支持。如0x53无法正确析。

### ISSUE THREAD

**Issue by jlzygs** [pengtianabc/wireshark-gm#20]
![图片](https://user-images.githubusercontent.com/49848076/126608471-eff73ea9-dbf2-48d8-8ee8-a45c55978639.png)
![图片](https://user-images.githubusercontent.com/49848076/126608618-6d289e9d-213c-4104-82a7-aaea2c307a60.png)

**Comment by pengtianabc** [comment]
这个应该是更新过的文档吧，以前做这个的时候还没这个文档，麻烦发一份呢。

**Comment by jlzygs** [comment]
***@***.***
 
发件人： pengtian
发送时间： 2021-08-12 23:04
收件人： pengtianabc/wireshark-gm
抄送： jlzygs; Author
主题： Re: [pengtianabc/wireshark-gm] GB/T 38636-2020 定义的密码套件不支持。如0x53无法正确析。 (#20)
这个应该是更新过的文档吧，以前做这个的时候还没这个文档，麻烦发一份呢。
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by pengtianabc** [comment]
什么情况。。。

**Comment by jlzygs** [comment]
> 
> 
> 这个应该是更新过的文档吧，以前做这个的时候还没这个文档，麻烦发一份呢。

https://www.tc260.org.cn/advice/detail.html?norm_id=20170320151522&norm_iso_id=GB/T%2038636%E2%80%942020

**Comment by sdhzdmzzl** [comment]
https://gitlab.com/wireshark/wireshark/-/merge_requests/5936
已提交官网，下个版本可能就可以了。
另外，作为360企业安全浏览器的开发人员，握个手
