### ISSUE TITLE
可以解密业务流量进行查看么

### ISSUE THREAD

**Issue by dramenk** [pengtianabc/wireshark-gm#23]
在配置了 主密钥 key log file 之后，可以支持基于 SM4 的业务流量解密查看么？

**Comment by pengtianabc** [comment]
不可以，wireshark底层没有接入SM4的算法（用的gnutls），所以无法解密

**Comment by dramenk** [comment]
感谢解惑

**Comment by zzl360** [comment]
wireshark4.0已支持国密协议的解密。windows下，wirehsark4.0带了1.10.1的libgcrypt，这个底层支持了国密。
