### ISSUE TITLE
谁能传几个实例数据包国密算法包数据包

### ISSUE THREAD

**Issue by shenggithub** [pengtianabc/wireshark-gm#3]
谁给发几个实例数据包做个测试.pcapng

**Comment by pengtianabc** [comment]
[gmssl2.zip](https://github.com/pengtianabc/wireshark-gm/files/2468227/gmssl2.zip)

**Comment by shenggithub** [comment]
给个带证书的数据包呗？好像国密标准的证书编号不识别！！！
