### ISSUE TITLE
exe是用什么软件生成的安装包？vs自带的么？还是什么打包工具？

### ISSUE THREAD

**Issue by shenggithub** [pengtianabc/wireshark-gm#5]

**Comment by pengtianabc** [comment]
手动编译的，详情百度wireshark的编译方法，也可以**参考**[我使用编译脚本](https://github.com/pengtianabc/wireshark-build)
注意：不保证在你的机器上能用，如果脚本有问题，请自行检查

**Comment by shenggithub** [comment]
已经编译完了，想打个exe安装包，在别的机器上安装。您用的什么软件做的安装包？nsis么？

**Comment by pengtianabc** [comment]
vs里面有一个子项目包含了打包步骤，需要安装nsis，建议直接装C盘，不然可能还要设置环境变量

wireshark-build项目-build.bat里：
`"%MSBUILD%" /m /p:Configuration=Release nsis_package_prep.vcxproj`
`"%MSBUILD%" /m /p:Configuration=Release nsis_package.vcxproj`
这两句就是编译打包的那个子项目
