### ISSUE TITLE
installer integrity check has failed

### ISSUE THREAD

**Issue by Zhang-Yuxin** [pengtianabc/wireshark-gm#8]
![qq 20190114233659](https://user-images.githubusercontent.com/46628690/51123702-9145c180-1857-11e9-84f9-40c2b7a488f4.png)

**Comment by pengtianabc** [comment]
I test `wireshark-2.9.0-gm.3` (md5: `d2bcda7c3ccd9b3ed7cd76b0fb480456`) again, it works. Please redownload. This error from nisis may because your installer is broken.
